project:
  type: website

website:
  title: "Life Long Learning Lab"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/petzi53/quarto-pb-blog
      - icon: twitter
        href: https://x.com/pbaumgartner
format:
  html:
    theme: cosmo
    css: styles.css



