---
title: "Privacy Policy"
date: 2023-05-01
draft: false
date-modified: 2024-07-19
---

Several places on this website require you to identify yourself:

## Comments

This Quarto website uses [Hypothesis](https://web.hypothes.is/) as a
commenting system. To control your data with Hypothesis, read
the [Hypothesis Privacy Policy](https://web.hypothes.is/privacy/).

## Contact

The contact form is a service by [formspree](https://formspree.io/).
They only store contents of the last 100 form submissions and delete the
rest. Formspree is [open source so that you can
check](https://github.com/formspree/formspree), what they are doing. The
emails themselves are sent using another [open
source](https://github.com/sendgrid) project: [SendGrid's
API](https://sendgrid.com/), so on that end, their [privacy
policies](https://sendgrid.com/policies/privacy/) apply.

By filling out the form, I get your name, email address, and your text.
I will do nothing except handling your mailed concern. I will delete all
mail sent by formspree at the latest after 12 months.

## Google Analytics

The only personal information collected while you visit this site is
non-identifying information, such as browser type and operating system.
This information is collected by [Google
Analytics](https://www.google.com/analytics/terms/us.html) for measuring
visitor traffic to this site.

For each visitor to reach the site, Google Analytics collects the
following non-personally identifiable information, including but not
limited to browser type, version and language, operating system, pages
viewed while browsing the site, page access times and referring website
address. This information is presented to me as aggregated reports to
gauge visitor traffic and trends.

This information is collected via cookies. Most web browsers allow you
to control the handling of cookies. To the best of my knowledge, you can
disable all cookies for this website without in any way reducing the
functionality for you. [Read here](https://cookiesandyou.com/) to learn
what cookies are and how to control or disable them.


```{=html}
<!-- Currently not in use
## Social sharing

If you are using the social sharing buttons on my website, then the privacy policy of those websites apply:

+ [Twitter](https://twitter.com/en/privacy)
+ [Facebook](https://www.facebook.com/privacy/explanation)
+ [Instagram](https://help.instagram.com/155833707900388)
+ [Weibo](https://www.whatsonweibo.com/privacy-policy/)

-->
```
